export const departmentsList = [
    "Administration",
    "Human Resources",
    "Finance and Accounting",
    "Marketing",
    "Sales",
    "Customer Service",
    "Information Technology (IT)",
    "Research and Development (R&D)",
    "Production or Manufacturing",
    "Quality Assurance",
    "Logistics and Supply Chain",
    "Legal",
    "Public Relations",
    "Facilities and Maintenance",
    "Health and Safety",
    "Training and Development",
    "Product Management",
    "Design and Creative Services",
    "Engineering",
    "Procurement"
];
